language: node_js
node_js: 10
cache: npm
before_script: node -r esm index.js &
after_success: npx apollo service:check
deploy:
  provider: script
  script: npx apollo service:push
  skip_cleanup: true
  on:
    branch: master
