name: Release docs

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Node CI]
    types:
      - completed

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: deploy-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.TAG_NAME }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          npx @magidoc/cli@latest generate --file ./docs/magidoc.mjs
          npx gh-pages --dist ./docs/build --dotfiles true
