name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and test
      run: |
        npm install
        npm test
    - name: Register schema
      run: |
        npx pm2 start index.js --node-args '-r esm'
        npx apollo service:push
      env:
        port: 5000
        engine_api_key: ${{ secrets.ENGINE_API_KEY }}
